### PR TITLE
Differentiate Leak Canary Activity labels

### PR DESCRIPTION
**Pull request by NightlyNexus**

### CODE REVIEW

**Comment by NightlyNexus** [comment]
Would it be good to change the task affinity as well?

**Comment by JakeWharton** [comment]
We moved this to a launcher shortcut internally to save the extra launcher icons.

**Comment by NightlyNexus** [comment]
I saw that change on internalDebug.
The launcher icon is still there on internalRelease. Intentional?
Should internal release's manifest be updated to include that change?

**Comment by JakeWharton** [comment]
Oh we made the change here too? It's hard to keep track of what gets sync'd
out. Internally we don't have leak detection enabled for internal release
builds so I'm not sure why it's enabled for this project.

**Comment by NightlyNexus** [comment]
>Internally we don't have leak detection enabled for internal release
builds
Oh, interesting.
I was actually going to try to figure out how to get heap dumps into Crashlytics (based on Py's GOTO talk) for internal builds.
I guess you have enough internal users to make a potential app freeze annoying?

**Comment by JakeWharton** [comment]
Yeah. We also have on-team testers using the internal debug build (which i
hate and is a long story). I guess it makes sense for internal release
builds to have leak analysis and perform uploading in an ideal case. It
would be nice if there was a callback when a leak was detected so that you
could display your own UI.

**Comment by NightlyNexus** [comment]
👍  Thanks! I was starting to think the same thing about various callbacks in LC, too. I'll see about filing a feature request after seeing what I want.

**Pull request merged**
