### PR TITLE
Register phoenix activity in manifest

### PR DESCRIPTION
**Pull request by mattprecious**
Oops.

### CODE REVIEW

**Comment by JakeWharton** [comment]
lgtm

**Comment by tasomaniac** [comment]
I wonder why did you decide to put separate process for this Activity.

**Comment by mattprecious** [comment]
The original process needs to be torn down for the object graph to be rebuilt and that can't happen if the `PhoenixActivity` is running in it.

**Comment by tasomaniac** [comment]
Wow thank you. Brilliant. This can be a really great library.

**Comment by mattprecious** [comment]
It already has a home on gist: https://gist.github.com/JakeWharton/9404647aa6a2b2818d22
There isn't enough there to warrant a full library.

**Comment by JakeWharton** [comment]
I've been tempted before to put this, rise and shine, etc. in micro libraries. Just to avoid copy/pasting and such. That's how Timber started.

**Pull request merged**
