### PR TITLE
Get rid of android-apt: we don't want to browse generated code

### PR DESCRIPTION
**Pull request by edenman**

### CODE REVIEW

**Comment by JakeWharton** [comment]
Not sure how I feel about this.

There's actually three things which using the `apt` configuration does compared to `provided`:
 * It adds the generated code as a source folder to IDEA
 * It does dependency resolution separately than dependencies used for compilation
 * It puts libraries and their dependencies on the `-processorpath` when invoking `javac`

You only really care about the first one because it's the most visual impact, but the last two are very important.

If `dagger-compiler` depends on "library A" version 2.0 but your app depends on "library A" version 1.4 then the "library A" dependency will get bumped to the potentially incompatible version solely to satisfy the code generator.

Worst of all, by using `provided` both the classes in the annotation processor and _all of its dependencies_ will be available for code-completion. This means that the Guava dependency that `dagger-compiler` has will be made available for your code to use. The problem here, as I'm sure you remember from when the struggle was real internally with this problem a while back, is that your code uses types which aren't bundled into the APK and end up failing at runtime.

I think what you want to do is get the android-apt plugin guy to do one of two things:
* Add an `aptOnly` configuration which omits adding the output folder as a source set.
* Add an Gradle extension which allows controlling whether the output folder is added as a source set.

**Comment by JakeWharton** [comment]
BTW that first sentence was a lie, I meant to delete it. The more I typed, the more sure I became!

**Comment by MichaelEvans** [comment]
@edenman I think we talked about this on Slack but you can exclude the build directory when doing Find Usages. (It doesn't work in the Open Class/Open File dialog, since IntelliJ doesn't support custom scopes there)

**Comment by MichaelEvans** [comment]
https://twitter.com/m_evans10/status/679325186966077440

**Pull request closed without merging**
