### PR TITLE
Add Strict Mode in debug builds

### PR DESCRIPTION
**Pull request by NightlyNexus**
#270

### CODE REVIEW

**Comment by NightlyNexus** [comment]
#271

**Comment by JakeWharton** [comment]
And does it run...?

**Comment by NightlyNexus** [comment]
Really sorry, I lazy-pasted here.
But, yes, I checked now, and it works.

Interestingly, you can successfully set Strict Mode in a static block. Just not in Application.onCreate.

**Comment by NightlyNexus** [comment]
er, sorry, i mean that Strict Mode works, not the app. i'm looking into it...

**Comment by NightlyNexus** [comment]
Strict Mode doesn't like Telescope hitting `getExternalFilesDir` in `cleanUp`. \0/
I guess that's not Telescope's responsibility. I see three options.
1) Throw `cleanUp` in an AsyncTask (gah) or something.
2) Set Strict Mode in the DebugViewContainer somewhere after `cleanUp`.
3) This is not worth it; close this nonsense PR.

**Comment by JakeWharton** [comment]
AsyncTask is fine. We do something similar internally.

**Comment by NightlyNexus** [comment]
getting caught on next case, the `inject` into DebugView. I'll have to take another stab at it tomorrow.

**Comment by NightlyNexus** [comment]
I don't have time to work on this. Linked in the issue for anybody that ever wants to do it.
Sorry for the noise.

**Pull request closed without merging**
