### PR TITLE
Strip image metadata to prevent build warning. Added script for it.

### PR DESCRIPTION
**Pull request by JakeWharton**

### CODE REVIEW

**Comment by mattprecious** [comment]
Why are all the colours slightly different?

**Comment by JakeWharton** [comment]
I think that's an illusion. Which specifically?

**Comment by mattprecious** [comment]
The launcher icon, the octocat image, basically everything. Change to the "swipe" view for the images instead of the SBS comparison. I think it's probably just a color profile thing that Android ignores but Chrome doesn't?

**Comment by mattprecious** [comment]
A random sampling around the office shows that my computer is the only one showing them differently... LGTM.

**Pull request merged**
