### PR TITLE
Update to AGP3-alpha8.

### PR DESCRIPTION
**Pull request by NightlyNexus**

### CODE REVIEW

**Comment by NightlyNexus** [comment]
Any idea what's missing here? I saw this failure in another project, so I think I'm missing something for Travis.

**Comment by mattprecious** [comment]
Build tools 26.0.0 were (accidentally?) deleted from maven. Need to update to 26.0.1.

**Comment by NightlyNexus** [comment]
Ah, thank you!

**Comment by NightlyNexus** [comment]
(kicking travis again.)

**Pull request merged**
